sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
#  - "3.2.1"
  - "4.0.0-rc.5"
  - development

# matrix:
#   allow_failures:
#     - haxe: development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix js # this generates an error in phantom but the tests are ok
  # - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php
